### PR TITLE
Fix Flag to display in WebGUI

### PR DESCRIPTION
**Pull request by tony-caffe**
Flag was not referenced correctly in code. Added the correct path to reflect it.

### CODE REVIEW

**Comment by furlongm** [comment]
How are you running openvpn-monitor?

It should get the image path from https://github.com/furlongm/openvpn-monitor/blob/master/openvpn-monitor.py#L748

**Comment by tony-caffe** [comment]
I am on CentOS 6.9 with Apache 2.2.15 and Python 2.6.6.

I get this error in my apache error log before the change: 

`[Fri Jul 21 12:22:13 2017] [error] [client 10.10.108.6] File does not exist: /var/www/html/openvpn-monitor/flags, referer: https://10.108.139.16:81/openvpn-monitor`

I was not getting a flag displayed, just the broken image default until I made the simple change. Could it be a Python version issue?

**Comment by furlongm** [comment]
Hmm, if you put a trailing slash on the URL, does it work?

**Comment by tony-caffe** [comment]
Yes it does! FYI there is a Issue generated by someone else to address this: https://github.com/furlongm/openvpn-monitor/issues/46

**Comment by tony-caffe** [comment]
When I do this trailing slash on the original code the flags appear but custom logo does not.

**Comment by furlongm** [comment]
Can you run in debug mode and show the generated html?

**Comment by tony-caffe** [comment]
Results for image in debug with command:

`python openvpn-monitor.py`

`<td>Corona, United States`

**Comment by furlongm** [comment]
And debug output for the logo part?

**Comment by tony-caffe** [comment]
Also here is the custom logo that gets removed only when trailing slash is added and appears as self.logo but when I remove the trailing slash, I lose the flags but logo reappears.

Here is the output from debug:
`<a href="#" class="pull-right">self.logo</a>`

**Comment by furlongm** [comment]
Did you include the full path to the logo in the config file? e.g. logo=images/mylogo.jpg

**Comment by tony-caffe** [comment]
Logo is in root directory so no path needed.

I did try to move the logo into the images/ directory but same issue.

**Comment by furlongm** [comment]
What is the apache error for the logo?

**Comment by tony-caffe** [comment]
There is no new error besides the one above.

**Comment by tony-caffe** [comment]
@furlongm 
```
10.10.108.6 - anthony [08/Aug/2017:09:19:26 -0700] "GET /flags/us.png HTTP/1.1" 404 210 "https://10.108.139.16:81/openvpn-monitor" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36"
```

**Comment by furlongm** [comment]
Sorry I meant you need a trailing slash. Does the error persist with a trailing slash?

**Comment by tony-caffe** [comment]
Yes for both. 

Custom logo that gets removed but flags appear only when trailing slash is added and appears as self.logo but when I remove the trailing slash, I lose the flags but logo reappears.

**Comment by vynhnx** [comment]
hey all, i have same problem
I follow https://github.com/furlongm/openvpn-monitor/pull/49/commits/60fb7a3197d45aea8082e83b41463606ed0028fe and EDITED, but flags can't show...
APACHE access.log
10.8.0.10 - - [19/Sep/2017:17:50:26 +0700] "GET /favicon.ico HTTP/1.1" 404 499 "http://10.8.0.1/vpn" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) coc_coc_browser/56.3.120 Chrome/50.3.2661.120 Safari/537.36"
my apache access.log
out put debug 
<td>Ho Chi Minh City, Vietnam

**Comment by furlongm** [comment]
If you do _not_ apply that patch, and use a trailing slash instead, does that fix it?

e.g. use http://10.8.0.1/vpn/ , not http://10.8.0.1/vpn

**Comment by vynhnx** [comment]
hi furlongm, i reinstall with default config, fix image/flags path and then access with http://10.8.0.1/openvpn-monitor/ but it don't fix.
this's apache accecss.log
10.8.0.6 - - [20/Sep/2017:11:40:05 +0700] "GET /openvpn-monitor/ HTTP/1.1" 200 2504 "http://10.8.0.1/openvpn-monitor/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
10.8.0.6 - - [20/Sep/2017:11:40:05 +0700] "GET /openvpn-monitor/images/flags/vn.png HTTP/1.1" 404 956 "http://10.8.0.1/openvpn-monitor/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
out put debug:
<td>Ho Chi Minh City, Vietnam
And VERSION.txt i'm using 1.0.0rc20. Now, any thing i need check...?

**Comment by vynhnx** [comment]
hi furlongm, i reinstall with default config, fix image/flags path and then access with http://10.8.0.1/openvpn-monitor/ but it don't fix.
this's apache accecss.log
10.8.0.6 - - [20/Sep/2017:11:40:05 +0700] "GET /openvpn-monitor/ HTTP/1.1" 200 2504 "http://10.8.0.1/openvpn-monitor/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
10.8.0.6 - - [20/Sep/2017:11:40:05 +0700] "GET /openvpn-monitor/images/flags/vn.png HTTP/1.1" 404 956 "http://10.8.0.1/openvpn-monitor/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
out put debug:
"<td>Ho Chi Minh City, Vietnam"
And VERSION.txt i'm using 1.0.0rc20. Now, any thing i need check...?

**Comment by furlongm** [comment]
Can you try _without_ this step: "fix image/flags path"?

It should not be needed to fix image/flags path.

**Comment by vynhnx** [comment]
hi furlongm, i reinstall with default config, fix image/flags path and then access with http://10.8.0.1/openvpn-monitor/ but it don't fix.
this's apache accecss.log
10.8.0.6 - - [20/Sep/2017:11:40:05 +0700] "GET /openvpn-monitor/ HTTP/1.1" 200 2504 "http://10.8.0.1/openvpn-monitor/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
10.8.0.6 - - [20/Sep/2017:11:40:05 +0700] "GET /openvpn-monitor/images/flags/vn.png HTTP/1.1" 404 956 "http://10.8.0.1/openvpn-monitor/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
out put debug:
Ho Chi Minh City, Vietnam
And VERSION.txt i'm using 1.0.0rc20. Now, any thing i need check...?

**Comment by vynhnx** [comment]
any thing ok, done...
thanks furlongm

**Comment by furlongm** [comment]
@vynhnx it works now?

**Comment by vynhnx** [comment]
@furlongm yes, ..that way ok
thanks you..

**Comment by furlongm** [comment]
Closing as I cannot reproduce the issue when using a trailing slash, and this change breaks stuff for me when I use it. Documentation is clearer about adding trailing slash now.

**Comment by ProtoSD** [comment]
I've been struggling with this same problem on Ubuntu 18.04.3 LTS, and OpenVPN 2.4.4 x86_64-pc-linux-gnu. This is what I changed that made it work for me:

Line #836:
`image_dir = '/usr/local/share/openvpn-monitor/images'`

Lines 865-867:
```
@app.route('/images/<filename:re:.*\.(jpg|png)>', method='GET')
def get_images(filename):
    return static_file(filename, root=image_dir)
```
I hardcoded the image_dir for testing, but I'm sure there's a better way to generate that. Both the flags and the Logo icon work correctly for me now.

**Comment by ProtoSD** [comment]
> ROUTING STATIC FILES¶
Static files such as images or CSS files are not served automatically. You have to add a route and a callback to control which files get served and where to find them:

from bottle import static_file
@route('/static/<filename>')
def server_static(filename):
    return static_file(filename, root='/path/to/your/static/files')
The static_file() function is a helper to serve files in a safe and convenient way (see Static Files). This example is limited to files directly within the /path/to/your/static/files directory **because the <filename> wildcard won’t match a path with a slash in it.** To serve files in subdirectories, change the wildcard to use the path filter:

@route('/static/<filepath:path>')
def server_static(filepath):
    return static_file(filepath, root='/path/to/your/static/files')

**Pull request closed without merging**
