### PR TITLE
Turns possible to set the configuration file to load through WSGI

### PR DESCRIPTION
**Pull request by thothix**
It turns possible to externaly set the configuration file through an environment variable.

### CODE REVIEW

**Comment by tiagobar** [comment]
What's the problem with the build!?

**Comment by DonDiego** [comment]
Why not just use the `--config` parameter? Seems plenty enough for me ...

**Comment by tiagobar** [comment]
> Why not just use the `--config` parameter? Seems plenty enough for me ...

Yes, it's fine if you run openvpn-monitor by command line, but if you use WSGI (I'm using gunicorn) you can't send parameters to it. If someone knows how to send arguments to openvpn-monitor through gunicorn without change the code, I'm willing to know.

**Comment by tiagobar** [comment]
I'm digging a bit running openvpn-monitor through gunicorm and I found a way that requires a smaller change in openvpn-monitor code although I think it's less elegant and even gunicorn documentation suggests to use environment variables to pass configuration data to applications.

The other way should be calling gunicorn like:
'''gunicorn 'openvpn-monitor:monitor_wsgi("/path-to/openvpn-monitor.conf")' -b 0.0.0.0:8080
'''

and a small change to monitor_wsgi() function:

'''def monitor_wsgi(config = ""):
    if config:
        args.config = config
   ...
'''

**Comment by DonDiego** [comment]
I'm still not convinced. You can just add the --config option in the place where openvpn-monitor gets called or put a wrapper in front of openvpn-monitor that calls the real script with the right --config parameter. But I'm not going to decide the fate of this pull request, so I'll bow out now.

**Pull request closed without merging**
